---
language: python
  - "3.7"
services:
  - docker
cache:
  - bundler
  - pip
env:
  global:
    - DOCKER_BUILDKIT=1
    - COMPOSE_FILE="$(pwd)/docker-compose.yml:$(pwd)/docker-compose.ci.yml"
before_script:
  - mkdir -p "$HOME/bin" "$HOME/.local/bin"
  - wget -qO- https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz | tar -xJv
  - mv 'shellcheck-stable/shellcheck' "$HOME/bin/shellcheck"
  - chmod +x "$HOME/bin/shellcheck"
  - cp -f scripts/dive "$HOME/bin/dive"
  - rvm install "$(cat .ruby-version)"
  - export PATH=$HOME/.local/bin:/usr/sbin:$PATH
script:
  - docker system prune --all --force --volumes
  - docker-compose pull
  - make docker-build install test
