---

language: python
python:
  - '2.7'
sudo: required
services:
  - docker
cache:
  - bundler
  - pip
before_script:
  - mkdir -p "$HOME/bin" "$HOME/.local/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - rvm install "$(cat .ruby-version)"
  - export PATH=$HOME/.local/bin:/usr/sbin:$PATH
script:
  - docker system prune --all --force --volumes
  - docker-compose build
  - make install test
