---
language: minimal
services:
  - docker
cache:
  - bundler
  - pip
env:
  - DOCKER_BUILDKIT=1
before_script:
  - mkdir -p "$HOME/bin" "$HOME/.local/bin"
  - wget -qO- 'https://storage.googleapis.com/shellcheck/shellcheck-v0.6.0.linux.x86_64.tar.xz' | tar -xJv
  - mv 'shellcheck-v0.6.0/shellcheck' "$HOME/bin/shellcheck"
  - chmod +x "$HOME/bin/shellcheck"
  - cp -f scripts/dive "$HOME/bin/dive"
  - rvm install "$(cat .ruby-version)"
  - export PATH=$HOME/.local/bin:/usr/sbin:$PATH
script:
  - docker system prune --all --force --volumes
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
  - make install test
