---

version: '3'
services:
  dnscrypt-proxy:
    network_mode: host
    ports:
      - 0.0.0.0:53:53/tcp
      - 0.0.0.0:53:53/udp
  tor:
    network_mode: host
    ports:
      - 0.0.0.0:9050:9050/tcp
      - 0.0.0.0:9053:9053/udp
