---
version: "3"
services:
  dnscrypt-proxy:
    network_mode: host
    ports:
      - 192.168.1.250:53:53/tcp
      - 192.168.1.250:53:53/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
  tor:
    network_mode: host
    ports:
      - 192.168.1.250:9050:9050/tcp
      - 192.168.1.250:9053:9053/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
  radicale:
    build: dockerfiles/radicale
    image: bdossantos/radicale
    container_name: radicale
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/radicale/data:/data
      - /volume1/docker/radicale/users:/config/users:ro
    shm_size: 8M
    ports:
      - 192.168.1.250:5232:5232/tcp
    network_mode: host
    restart: always
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
    network_mode: host
    ports:
      - 192.168.1.250:3000:3000/tcp
    environment:
      - GF_INSTALL_PLUGINS=grafana-strava-datasource,grafana-worldmap-panel
      - GF_PLUGINS_ENABLE_ALPHA=true
      - GF_STRAVA_DS_DATA_PATH=/var/lib/grafana/strava
    restart: always
