---

version: '3'
services:
  dnscrypt-proxy:
    build: dockerfiles/dnscrypt-proxy
    image: bdossantos/dnscrypt-proxy
    container_name: dnscrypt-proxy
    read_only: true
    shm_size: 32M
    ports:
      - 127.0.0.1:5300:53/udp
  tor:
    build: dockerfiles/tor
    image: bdossantos/tor
    container_name: tor
    read_only: true
    shm_size: 32M
    ports:
      - 127.0.0.1:9050:9050/tcp
      - 127.0.0.1:9053:9053/udp

networks:
  default:
    driver: bridge
